### ISSUE TITLE
‫اضافه کردن فونت به TCPDF

### ISSUE THREAD

**Issue by hbsoftco** [ooghry/TCPDF-Persian-Farsi-font#1]
سلام
من چطور می تونم فونت فارسی رو به این پکیج تو لاراول اضافه کنم؟
هر کاری می کنم نمیشه
ممنون میشم اگه دستورالعمل افزودن فونت رو هم قرار بدین.
با تشکر

**Comment by ooghry** [comment]
سلام
باید از متد
setFont
استفاده کنی.
مثلا
$pdf->SetFont('hiwebmitra', '', 14);
این آدرس هم ببین:
https://stackoverflow.com/a/40198014

**Comment by ooghry** [comment]
#2

**Comment by akoweb** [comment]
https://github.com/akoweb/tcpdf
